import os
from typing import List
from app.logging import logger
from app.services.notification.gmail import gmail_notification_service

class GmailMCPClient:
    """Standardized Gmail MCP Connector to manage communications via email payloads."""
    def __init__(self):
        self.mode = os.getenv("GMAIL_MCP_MODE", "mock").lower()
        self.is_mock = self.mode == "mock"
        logger.info(f"Gmail MCP loaded in {self.mode.upper()} mode.")

    def send_medication_reminder(
        self, 
        caregiver_email: str, 
        patient_name: str, 
        med_name: str, 
        dosage: str
    ) -> bool:
        subject = f"MedAssist Compliance Alert: {patient_name} Missed Medication"
        body = (
            f"Dear Caregiver,\n\n"
            f"This is an automated notification from MedAssist AI. "
            f"Patient {patient_name} has missed their scheduled dosage of {med_name} ({dosage}).\n"
            f"Please check in with them regarding compliance."
        )
        return self._dispatch(caregiver_email, subject, body)

    def send_caregiver_notification(
        self, 
        caregiver_email: str, 
        patient_name: str, 
        subject: str, 
        message: str
    ) -> bool:
        full_subject = f"MedAssist Notice: {subject}"
        body = (
            f"Dear Caregiver,\n\n"
            f"Update regarding patient {patient_name}:\n"
            f"{message}\n\n"
            f"Best regards,\nMedAssist Concierge Service"
        )
        return self._dispatch(caregiver_email, full_subject, body)

    def send_report_summary(
        self,
        caregiver_email: str,
        patient_name: str,
        filename: str,
        summary: str
    ) -> bool:
        subject = f"MedAssist Report Summary: {filename} for {patient_name}"
        body = (
            f"Dear Caregiver,\n\n"
            f"Here is the summarized diagnostic extraction of the report '{filename}' "
            f"uploaded for patient {patient_name}:\n\n"
            f"{summary}\n\n"
            f"Disclaimer: This summary is generated by an AI assistant and should not substitute medical consults."
        )
        return self._dispatch(caregiver_email, subject, body)

    def _dispatch(self, recipient: str, subject: str, body: str) -> bool:
        if self.is_mock:
            logger.info(
                f"[MOCK GMAIL MCP ALERT]\n"
                f"To: {recipient}\n"
                f"Subject: {subject}\n"
                f"Content: {body}"
            )
            return True
            
        # Invoke real SMTP delivery pipeline
        return gmail_notification_service.send_alert(recipient, subject, body)

gmail_mcp = GmailMCPClient()
